config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'calculators#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :calculators, only: [:index]
  post '/calculate', to: 'calculators#calculate', as: :calculate
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculators_controller.rb
class CalculatorsController < ApplicationController
  before_action :authenticate_user!

  def index
    @funds = Funds.all_funds
  end

  def calculate
    @fund = Funds.all_funds[params[:fund_name]]
    render status: :not_found && return unless @fund && @fund[Funds::SHARE_CLASS_R6].present?

    @fund_name = params[:fund_name]
    @aum = params[:aum].to_f
    @num_accounts = params[:num_accounts].to_i
    @cash = params[:cash].to_f
    @num_trades_per_year = params[:num_trades_per_year].to_f
    @cost_per_trade = params[:cost_per_trade].to_f

    render :show
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calculators/index.haml
.grid-x
  .cell.small-2
  .cell.small-8
    = form_with url: calculate_path, local: true do |f|
      = label_tag 'fund_name', 'Mutual Fund:'
      = text_field_tag 'fund_name', nil, placeholder: 'Fund name', id: 'fund_name'

      = label_tag :aum, 'Assets Under Management (in dollars):'
      = text_field_tag :aum, nil, placeholder: 'Assets Under Management'

      = label_tag :mutual_fund_percentage, 'Percent of AUM in mutual funds:'
      = text_field_tag :mutual_fund_percentage, nil, placeholder: '% of AUM in mutual funds'

      = label_tag :cash, 'Cash balance (in dollars):'
      = text_field_tag :cash, nil, placeholder: 'Cash balance'

      = label_tag :num_accounts, 'Number of accounts:'
      = text_field_tag :num_accounts, nil, placeholder: 'Number of accounts'

      %h5 Trading costs
      %p.help-text Leave blank if no costs to trade
      = label_tag :num_trades_per_year, 'Number of Trades Per Year:'
      = text_field_tag :num_trades_per_year, nil, placeholder: 'Number of trades per year'

      = label_tag :cost_per_trade, 'Cost per trade:'
      = text_field_tag :cost_per_trade, nil, placeholder: 'Cost per trade'

      = submit_tag 'Calculate'

  .cell.small-2

:javascript
  $('#fund_name').autocomplete({
    source: #{@funds.keys.to_s.html_safe},
    classes: {'ui-autocomplete': 'no-bullet'}
    });

app/views/calculators/show.haml
.grid-x
  .cell-2
    .grid-y
      .cell.small-1
      .cell.small-10{style: 'border: 1px solid black; padding: 5px;'}
        %h3
          = "#{@fund_name} #{Funds::SHARE_CLASS_R6}"
        %p
          Transparent Fees Paid to
          %br
          New Platform - Entrustody:
        .grid-y
          .cell.small-2{style: 'border-top: 1px solid black; border-bottom: 1px solid black;'}
            %p
              Expense Ratio:
              %br
              = number_to_percentage(@fund[Funds::SHARE_CLASS_R6][:exp_ratio], precision: 4)
          .cell.small-2{style: 'border-top: 1px solid black; border-bottom: 1px solid black;'}
            %p
              Trading Costs
              %br
              - trading_costs = @num_accounts * @num_trades_per_year * 0.5
              = number_to_currency(trading_costs)
          .cell.small-2{style: 'border-top: 1px solid black; border-bottom: 1px solid black;'}
            %p
              Single Platform Fee:
              %br
              - platform_fee = @num_accounts * 15
              = number_to_currency(platform_fee)
          .cell.small-2{style: 'border-top: 1px solid black; border-bottom: 1px solid black;'}
            %p
              Total cost on new platform:
              %br
              %span{style: "background-color: yellow;"}
                = number_to_currency((@aum - @cash) * @fund[Funds::SHARE_CLASS_R6][:exp_ratio] + platform_fee + trading_costs)

  - (Funds::SHARE_CLASSES - [Funds::SHARE_CLASS_R6]).each do |share_class|
    - next unless @fund[share_class]
    .cell-2
      .grid-y
        .cell.small-1
        .cell.small-10{style: 'border: 1px solid black; padding: 5px;'}
          %h3
            = "#{@fund_name} #{share_class}"
          %p
            Extimated Current Fees Being Paid
            %br
            to Custudian/Broker Dealer
          .grid-y
            .cell.small-2{style: 'border-top: 1px solid black; border-bottom: 1px solid black;'}
              %p
                Expense Ratio:
                %br
                = number_to_percentage(@fund[share_class][:exp_ratio], precision: 4)
          .cell.small-2{style: 'border-top: 1px solid black; border-bottom: 1px solid black;'}
            %p
              Trading Costs
              %br
              - trading_costs = @num_accounts * @num_trades_per_year * @cost_per_trade
              = number_to_currency(trading_costs)
          .cell.small-2{style: 'border-top: 1px solid black; border-bottom: 1px solid black;'}
            %p
              Cash Spread Cost (Opportunity cost)
              %br
              - opp_cost = @cash * 0.02
              = number_to_currency(opp_cost)
          .cell.small-2{style: 'border-top: 1px solid black; border-bottom: 1px solid black;'}
            %p
              Total cost of current platform:
              %br
              %span{style: "background-color: yellow;"}
                = number_to_currency((@aum - @cash) * @fund[share_class][:exp_ratio] + trading_costs + opp_cost)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Entrustody</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

    <!-- Compressed CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.5.1/dist/css/foundation.min.css" integrity="sha256-1mcRjtAxlSjp6XJBgrBeeCORfBp/ppyX4tsvpQVCcpA= sha384-b5S5X654rX3Wo6z5/hnQ4GBmKuIJKMPwrJXn52ypjztlnDK2w9+9hSMBz/asy9Gw sha512-M1VveR2JGzpgWHb0elGqPTltHK3xbvu3Brgjfg4cg5ZNtyyApxw/45yHYsZ/rCVbfoO5MSZxB241wWq642jLtA==" crossorigin="anonymous">

    <!-- Compressed JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/foundation-sites@6.5.1/dist/js/foundation.min.js" integrity="sha256-WUKHnLrIrx8dew//IpSEmPN/NT3DGAEmIePQYIEJLLs= sha384-53StQWuVbn6figscdDC3xV00aYCPEz3srBdV/QGSXw3f19og3Tq2wTRe0vJqRTEO sha512-X9O+2f1ty1rzBJOC8AXBnuNUdyJg0m8xMKmbt9I3Vu/UOWmSg5zG+dtnje4wAZrKtkopz/PEDClHZ1LXx5IeOw==" crossorigin="anonymous"></script>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>